name: la3bob
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  result_dart: ^2.1.1
  multiple_result: ^5.2.0
  dart_mappable: ^4.6.1
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  get_it: ^9.0.5
  injectable: ^2.6.0
  get_storage: ^2.1.1
  flutter_bloc: ^9.1.1
  uuid: ^4.5.2
  gap: ^3.0.1
  go_router: ^17.0.0
  pinput: ^5.0.2
  video_player: ^2.9.1
  youtube_player_flutter: ^9.0.0
  flutter_localizations:
    sdk: flutter
  babstrap_settings_screen: ^0.1.7
  kiosk_mode: ^0.7.0+1
  local_auth: ^3.0.0
  fluttertoast: ^9.0.0
  local_auth_android: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  dart_mappable_builder: ^4.6.1
  injectable_generator: ^2.6.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
